defmodule PerplexicaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :perplexica

  # Signed cookie session. Rotating SECRET_KEY_BASE invalidates all active
  # sessions (the derived signing key changes). 30-day max age, HttpOnly,
  # SameSite=Lax, Secure in prod.
  @session_options [
    store: :cookie,
    key: "_perplexica_key",
    signing_salt: "teJ5EcuW",
    same_site: "Lax",
    http_only: true,
    secure: Mix.env() == :prod,
    max_age: 60 * 60 * 24 * 30
  ]

  # Public accessor so the router pipeline can reuse the same options.
  def session_options, do: @session_options

  # Absinthe WebSocket for GraphQL subscriptions
  use Absinthe.Phoenix.Endpoint

  socket "/socket", PerplexicaWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :perplexica,
    gzip: not code_reloading?,
    only: PerplexicaWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :perplexica
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PerplexicaWeb.Router
end
